name: Build Portfolio application

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build entire project
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        env:
          MESSAGE: Launching the Maven build for the Portfolio application
        run: |
          echo $MESSAGE.
      - name: run mvn install
        working-directory: ./portfolio
        run: |
          mvn clean install

  npm_build:
    name: Build front
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        env:
          MESSAGE: Launching the npm build for the Portfolio-client application
        run: |
          echo $MESSAGE.
      - name: run npm install 
        working-directory: ./portfolio/portfolio-client
        run: |
          npm install
      - name: run npm build
        working-directory: ./portfolio/portfolio-client
        run: |
          npm run build
